# Generated by Django 6.0.8 on 2026-09-24 05:18

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshift',
            name='vehicle',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'SALES_VEHICLE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_shifts', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='roleprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to='auth.group'),
        ),
        migrations.AddConstraint(
            model_name='customusermodel',
            constraint=models.CheckConstraint(condition=models.Q(('username__contains', '@'), _negated=True), name='accounts_user_username_not_at'),
        ),
        migrations.AddConstraint(
            model_name='customusermodel',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='accounts_user_email_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='customusermodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.UniqueConstraint(fields=('employee', 'business_date'), name='accounts_employee_shift_employee_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('employee',), name='accounts_one_open_shift_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closing_cash__isnull', True), ('closing_transfer__isnull', True), ('status', 'open')), models.Q(('closed_at__isnull', False), ('closing_cash__isnull', False), ('closing_transfer__isnull', False), ('status', 'closed')), _connector='OR'), name='accounts_employee_shift_status_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_cash__gte', 0)), name='accounts_employee_shift_opening_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.CheckConstraint(condition=models.Q(('closing_cash__isnull', True), ('closing_cash__gte', 0), _connector='OR'), name='accounts_employee_shift_closing_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.CheckConstraint(condition=models.Q(('closing_transfer__isnull', True), ('closing_transfer__gte', 0), _connector='OR'), name='accounts_employee_shift_closing_transfer_non_negative'),
        ),
    ]
