# Generated by Django 6.0.8 on 2026-09-10 02:56

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=250)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('website', models.URLField(blank=True)),
                ('singleton_marker', models.BooleanField(default=True, editable=False)),
                ('product_count', models.PositiveBigIntegerField(default=0)),
                ('invoice_count', models.PositiveBigIntegerField(default=0)),
                ('customer_count', models.PositiveBigIntegerField(default=0)),
                ('supplier_count', models.PositiveBigIntegerField(default=0)),
                ('counters_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_marker', True)), name='organization_company_singleton_marker_true'), models.UniqueConstraint(fields=('singleton_marker',), name='organization_only_one_company')],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('site_type', models.CharField(choices=[('head_office', 'Head office'), ('branch', 'Branch'), ('store', 'Store')], max_length=20)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state_or_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Enter a valid two-letter country code.', regex='^[A-Za-z]{2}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organization.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.site')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.company')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('company'), name='organization_site_company_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(condition=models.Q(('site_type', 'head_office')), fields=('company',), name='organization_one_head_office_per_company'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('site_type', 'store'), ('parent__isnull', True), _connector='OR'), name='organization_only_store_may_have_parent'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('company'), name='organization_department_company_code_ci_unique'),
        ),
    ]
