# Generated by Django 6.0.8 on 2026-09-10 02:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('coupons', '0001_initial'),
        ('customers', '0001_initial'),
        ('organization', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('returned', 'Returned')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coupons.coupon')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.employeeshift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='organization.site')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('confirm_invoice', 'Can confirm an invoice'), ('cancel_invoice', 'Can cancel an invoice'), ('apply_invoice_coupon', 'Can apply a coupon to an invoice'), ('return_invoice', 'Can return items from a paid invoice')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoice_returns', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='invoices.invoice')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_returns', to='accounts.employeeshift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_returns', to='organization.site')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('condition', models.CharField(choices=[('saleable', 'Saleable')], default='saleable', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='invoices.invoiceitem')),
                ('invoice_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoicereturn')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'created_at'], name='invoice_cust_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['site', 'created_at'], name='invoice_site_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['shift', 'created_at'], name='invoice_shift_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('coupon_discount__gte', Decimal('0'))), name='invoice_coupon_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'product'), name='invoices_unique_invoice_product'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='invoice_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0'))), name='invoice_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', Decimal('0')), ('cost_price__isnull', True), _connector='OR'), name='invoice_item_cost_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='invoicereturn',
            index=models.Index(fields=['site', 'created_at'], name='iret_site_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicereturn',
            index=models.Index(fields=['shift', 'created_at'], name='iret_shift_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicereturn',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', Decimal('0'))), name='invoice_return_refund_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoicereturnitem',
            constraint=models.UniqueConstraint(fields=('invoice_return', 'invoice_item'), name='invoice_return_item_unique_line'),
        ),
        migrations.AddConstraint(
            model_name='invoicereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='invoice_return_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='invoice_return_item_price_non_negative'),
        ),
    ]
