# Generated by Django 6.0.8 on 2026-09-24 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_accounting_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_periods', to='organization.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='organization.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='organization.company'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'account_type'], name='acct_company_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='accounting_account_company_code_unique'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['company', 'start_date', 'end_date'], name='acct_period_company_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('company', 'start_date', 'end_date'), name='accounting_period_company_dates_unique'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'expense_date'], name='expense_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'entry_date'], name='journal_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'status'], name='journal_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='journal_source_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='journal_entry_company_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'source_type', 'source_id'), name='journal_entry_company_source_unique'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'entry'], name='journal_line_account_entry_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='journal_line_exactly_one_side'),
        ),
    ]
