# Generated by Django 6.0.8 on 2026-09-10 02:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_value__lt', Decimal('0')), _negated=True), name='coupon_discount_value_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), ('discount_value__lte', Decimal('100'))), models.Q(('discount_type', 'percentage'), _negated=True), _connector='OR'), name='coupon_discount_percentage_max_100'), models.CheckConstraint(condition=models.Q(('minimum_invoice_amount__isnull', True), models.Q(('minimum_invoice_amount__lt', Decimal('0')), _negated=True), _connector='OR'), name='coupon_minimum_invoice_amount_non_negative')],
            },
        ),
    ]
