# Generated by Django 6.0.8 on 2026-09-10 02:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchases', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='accounts.employeeshift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='organization.site')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('confirm_purchase', 'Can confirm purchase'), ('cancel_purchase', 'Can cancel purchase'), ('return_purchase', 'Can return items from a purchase'), ('process_supplier_payment', 'Can process a supplier payment')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.inventorybatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchase')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='accounts.employeeshift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='organization.site')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='purchases.purchaseitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_made', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='accounts.employeeshift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='organization.site')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchases.supplierpayment')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_allocations', to='purchases.purchase')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['site', 'created_at'], name='purchase_site_created_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['shift', 'created_at'], name='purchase_shift_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.UniqueConstraint(fields=('purchase', 'product'), name='purchase_item_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='purchase_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_purchase_price__gte', 0)), name='purchase_item_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('manufactured_date__isnull', True), ('expiry_date__gte', models.F('manufactured_date')), _connector='OR'), name='purchase_item_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['site', 'created_at'], name='pret_site_created_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['shift', 'created_at'], name='pret_shift_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnitem',
            constraint=models.UniqueConstraint(fields=('purchase_return', 'purchase_item'), name='purchase_return_item_unique_line'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='purchase_return_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_return_item_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'created_at'], name='suppay_supplier_created_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['site', 'created_at'], name='suppay_site_created_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['shift', 'created_at'], name='suppay_shift_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount__gte', Decimal('0'))), name='supplier_payment_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_amount__gte', Decimal('0'))), name='supplier_payment_transfer_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount__gt', Decimal('0')), ('transfer_amount__gt', Decimal('0')), _connector='OR'), name='supplier_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'purchase'), name='supplier_payment_alloc_payment_purchase_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount__gte', Decimal('0'))), name='supplier_payment_alloc_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_amount__gte', Decimal('0'))), name='supplier_payment_alloc_transfer_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount__gt', Decimal('0')), ('transfer_amount__gt', Decimal('0')), _connector='OR'), name='supplier_payment_alloc_amount_positive'),
        ),
    ]
