# Generated by Django 6.0.8 on 2026-09-10 02:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='products.product')),
            ],
            options={
                'ordering': ('expiry_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location_type', models.CharField(choices=[('MAIN_WAREHOUSE', 'Main Warehouse'), ('SALES_VEHICLE', 'Sales Vehicle')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_location', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_locations', to='organization.site')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockBatchBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.inventorybatch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batch_balances', to='inventory.stocklocation')),
            ],
            options={
                'ordering': ('batch__expiry_date', 'batch_id'),
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='products.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='inventory.stocklocation')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('PURCHASE_RETURN', 'Purchase Return'), ('TRANSFER', 'Transfer'), ('SALE', 'Sale'), ('SALEABLE_RETURN', 'Saleable Return'), ('DAMAGED_RETURN', 'Damaged Return')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='inventory.stocklocation')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='accounts.employeeshift')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='inventory.stocklocation')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('transfer_stock', 'Can transfer stock')],
            },
        ),
        migrations.CreateModel(
            name='StockMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Historical inventory cost per unit captured at movement time.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_items', to='inventory.inventorybatch')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement_items', to='products.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['product', 'expiry_date'], name='inventory_batch_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_number__isnull', False)), fields=('product', 'batch_number'), name='inventory_batch_product_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('manufactured_date__isnull', True), ('expiry_date__gte', models.F('manufactured_date')), _connector='OR'), name='inventory_batch_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('location_type', 'MAIN_WAREHOUSE'), ('site__isnull', False)), fields=('site',), name='inventory_one_active_main_warehouse_per_site'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('location_type', 'MAIN_WAREHOUSE'), ('site__isnull', True)), fields=('location_type',), name='inventory_one_legacy_main_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockbatchbalance',
            index=models.Index(fields=['location', 'quantity'], name='sbb_loc_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatchbalance',
            index=models.Index(fields=['batch', 'location'], name='sbb_batch_loc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatchbalance',
            constraint=models.UniqueConstraint(fields=('location', 'batch'), name='stock_batch_balance_unique_location_batch'),
        ),
        migrations.AddConstraint(
            model_name='stockbatchbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_batch_balance_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbatchbalance',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', Decimal('0'))), name='stock_batch_balance_total_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('location', 'product'), name='stock_balance_unique_location_product'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', Decimal('0'))), name='stock_balance_total_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination_location__isnull', False), ('movement_type', 'TRANSFER'), ('source_location__isnull', False)), models.Q(('destination_location__isnull', True), ('movement_type__in', ('PURCHASE_RETURN', 'SALE')), ('source_location__isnull', False)), models.Q(('destination_location__isnull', False), ('movement_type__in', ('PURCHASE', 'SALEABLE_RETURN', 'DAMAGED_RETURN')), ('source_location__isnull', True)), _connector='OR'), name='stock_movement_direction_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'TRANSFER'), ('source_location__isnull', True)), models.Q(('source_location', models.F('destination_location')), _negated=True), _connector='OR'), name='stock_transfer_locations_differ'),
        ),
        migrations.AddIndex(
            model_name='stockmovementitem',
            index=models.Index(fields=['product', 'movement'], name='stock_move_item_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovementitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='stock_movement_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovementitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0), ('unit_cost__isnull', True), _connector='OR'), name='stock_movement_item_unit_cost_non_negative'),
        ),
    ]
