import { useEffect, useState } from 'react';
import { DatePickerInput } from '@mantine/dates';
import { Badge, Card, Group, Loader, SimpleGrid, Stack, Text, Title } from '@mantine/core';
import { notifications } from '@mantine/notifications';

import { CrudPage } from '../components/CrudPage';
import { RecordsPage } from '../components/RecordsPage';
import { api, query } from '../lib/api';

const money = (value: unknown) => Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function AccountingHomePage() {
  const [loading, setLoading] = useState(true);
  const [pnl, setPnl] = useState<Record<string, unknown> | null>(null);
  const [bs, setBs] = useState<Record<string, unknown> | null>(null);

  useEffect(() => {
    Promise.all([api.accounting.profitAndLoss(), api.accounting.balanceSheet(new Date().toISOString().slice(0, 10))])
      .then(([profit, balance]) => { setPnl(profit as Record<string, unknown>); setBs(balance as Record<string, unknown>); })
      .catch((error) => notifications.show({ title: 'Accounting unavailable', message: error instanceof Error ? error.message : 'Request failed.', color: 'red' }))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <Card className="glass" radius="lg" p={60} withBorder><Group justify="center"><Loader /></Group></Card>;

  return (
    <Stack gap="xl">
      <div><Text size="sm" c="indigo.3" fw={800}>ACCOUNTING</Text><Title order={1} mt={4}>Financial command center</Title><Text c="dimmed" mt={4}>The accounting layer is driven by posted journals and business transactions.</Text></div>
      <SimpleGrid cols={{ base: 1, sm: 2, lg: 4 }}>
        <Card className="glass bento-card" radius="lg" withBorder><Text c="dimmed" size="xs" tt="uppercase" fw={800}>Revenue</Text><Text fw={900} size="2rem" mt={6}>{money(pnl?.total_revenue)}</Text></Card>
        <Card className="glass bento-card" radius="lg" withBorder><Text c="dimmed" size="xs" tt="uppercase" fw={800}>Expenses</Text><Text fw={900} size="2rem" mt={6}>{money(pnl?.total_expenses)}</Text></Card>
        <Card className="glass bento-card" radius="lg" withBorder><Text c="dimmed" size="xs" tt="uppercase" fw={800}>Net income</Text><Text fw={900} size="2rem" mt={6}>{money(pnl?.net_income)}</Text></Card>
        <Card className="glass bento-card" radius="lg" withBorder><Group justify="space-between"><div><Text c="dimmed" size="xs" tt="uppercase" fw={800}>Balance</Text><Text fw={900} size="2rem" mt={6}>{money(bs?.total_assets)}</Text></div><Badge color={bs?.balanced ? 'teal' : 'red'}>{bs?.balanced ? 'Balanced' : 'Check'}</Badge></Group></Card>
      </SimpleGrid>
    </Stack>
  );
}

export function AccountsPage() {
  return (
    <CrudPage
      title="Accounts"
      subtitle="Chart of accounts used by the posting engine and reports."
      list={api.accounting.accounts}
      create={api.accounting.createAccount}
      update={api.accounting.updateAccount}
      remove={async () => undefined}
      fields={[{ key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'account_type', label: 'Account type', required: true }, { key: 'is_active', label: 'Active', type: 'boolean' }]}
      columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Account' }, { key: 'account_type', label: 'Type' }, { key: 'is_active', label: 'Status' }]}
    />
  );
}

export function JournalsPage() {
  return (
    <RecordsPage
      eyebrow="ACCOUNTING"
      title="Journal entries"
      subtitle="Posted and draft accounting entries generated by ERP operations."
      list={api.accounting.journalEntries}
      columns={[{ key: 'number', label: '#' }, { key: 'entry_date', label: 'Date' }, { key: 'description', label: 'Description' }, { key: 'reference', label: 'Reference' }, { key: 'status', label: 'Status' }]}
    />
  );
}

export function StatementsPage() {
  const [from, setFrom] = useState<Date | null>(new Date(new Date().getFullYear(), 0, 1));
  const [to, setTo] = useState<Date | null>(new Date());
  const [data, setData] = useState<Record<string, Record<string, unknown>> | null>(null);
  const [loading, setLoading] = useState(false);

  async function load() {
    if (!from || !to) return;
    setLoading(true);
    try {
      const params = query({ from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) });
      const asOf = to.toISOString().slice(0, 10);
      const [pnl, bs, cf] = await Promise.all([
        api.accounting.profitAndLoss(params),
        api.accounting.balanceSheet(asOf),
        api.accounting.cashFlow(params),
      ]);
      setData({ pnl: pnl as Record<string, unknown>, bs: bs as Record<string, unknown>, cf: cf as Record<string, unknown> });
    } catch (error) {
      notifications.show({ title: 'Report failed', message: error instanceof Error ? error.message : 'Request failed.', color: 'red' });
    } finally { setLoading(false); }
  }

  useEffect(() => { void load(); }, []);

  return (
    <Stack gap="xl">
      <Group justify="space-between" align="flex-end" wrap="wrap"><div><Text size="sm" c="indigo.3" fw={800}>ACCOUNTING</Text><Title order={1} mt={4}>Financial statements</Title><Text c="dimmed" mt={4}>P&L, balance sheet and cash flow from posted journal activity.</Text></div><ButtonLoad loading={loading} onClick={load} /></Group>
      <Group grow maw={700}><DatePickerInput label="From" value={from} onChange={setFrom} /><DatePickerInput label="To" value={to} onChange={setTo} /></Group>
      {!data ? <Text c="dimmed">Select a range and load the statements.</Text> : <SimpleGrid cols={{ base: 1, md: 3 }}>
        <Card className="glass" withBorder radius="lg"><Text fw={800}>P&L</Text><Text size="sm" c="dimmed" mt="md">Revenue</Text><Text fw={800} size="xl">{money(data.pnl.total_revenue)}</Text><Text size="sm" c="dimmed" mt="md">Expenses</Text><Text fw={800} size="xl">{money(data.pnl.total_expenses)}</Text><Text size="sm" c="dimmed" mt="md">Net income</Text><Text fw={900} size="2xl">{money(data.pnl.net_income)}</Text></Card>
        <Card className="glass" withBorder radius="lg"><Text fw={800}>Balance sheet</Text><Text size="sm" c="dimmed" mt="md">Assets</Text><Text fw={900} size="2xl">{money(data.bs.total_assets)}</Text><Text size="sm" c="dimmed" mt="md">Liabilities</Text><Text fw={800} size="xl">{money(data.bs.total_liabilities)}</Text><Badge mt="md" color={data.bs.balanced ? 'teal' : 'red'}>{data.bs.balanced ? 'Balanced' : 'Unbalanced'}</Badge></Card>
        <Card className="glass" withBorder radius="lg"><Text fw={800}>Cash flow</Text><Text size="sm" c="dimmed" mt="md">Opening</Text><Text fw={800} size="xl">{money(data.cf.opening_cash)}</Text><Text size="sm" c="dimmed" mt="md">Net change</Text><Text fw={900} size="2xl">{money(data.cf.net_change)}</Text><Text size="sm" c="dimmed" mt="md">Ending</Text><Text fw={800} size="xl">{money(data.cf.ending_cash)}</Text></Card>
      </SimpleGrid>}
    </Stack>
  );
}

function ButtonLoad({ loading, onClick }: { loading: boolean; onClick: () => void }) {
  return <button className="unstyled-action" onClick={onClick} disabled={loading}>{loading ? 'Loading…' : 'Refresh statements'}</button>;
}

export function BalancesPage() {
  return (
    <RecordsPage
      eyebrow="ACCOUNTING"
      title="AR / AP balances"
      subtitle="Customer and supplier balances from the operational ledger."
      list={async (queryString) => {
        const [customers, suppliers] = await Promise.all([api.accounting.customerBalances(queryString), api.accounting.supplierBalances(queryString)]);
        const customerRows = Array.isArray(customers) ? customers : [];
        const supplierRows = Array.isArray(suppliers) ? suppliers : [];
        return { count: customerRows.length + supplierRows.length, next: null, previous: null, results: [
          ...customerRows.map((row: Record<string, unknown>) => ({ ...row, party_type: 'Customer', party_name: row.customer_name })),
          ...supplierRows.map((row: Record<string, unknown>) => ({ ...row, party_type: 'Supplier', party_name: row.supplier_name })),
        ] };
      }}
      columns={[{ key: 'party_type', label: 'Type' }, { key: 'party_name', label: 'Party' }, { key: 'invoiced', label: 'Invoiced' }, { key: 'purchased', label: 'Purchased' }, { key: 'paid', label: 'Paid' }, { key: 'balance', label: 'Balance' }]}
    />
  );
}
