import type { FormEvent } from 'react';
import { useEffect, useMemo, useState } from 'react';
import { Button, Card, Divider, Group, NumberInput, Select, SimpleGrid, Stack, Text, TextInput, Title } from '@mantine/core';
import { notifications } from '@mantine/notifications';

import { api, type Paginated, type UserProfile } from '../lib/api';

type Line = { product: string; quantity: number | string; unit_purchase_price?: number | string; batch_number?: string; manufactured_date?: string; expiry_date?: string };
function useOptions(loadSites = false) {
  const empty = { count: 0, next: null, previous: null, results: [] } as Paginated;
  const [products, setProducts] = useState<Paginated>(empty); const [customers, setCustomers] = useState<Paginated>(empty); const [suppliers, setSuppliers] = useState<Paginated>(empty); const [sites, setSites] = useState<Paginated>(empty);
  useEffect(() => { const requests: Promise<unknown>[] = [api.products.list('?page_size=50'), api.customers.list('?page_size=50'), api.suppliers.list('?page_size=50')]; if (loadSites) requests.push(api.organization.sites('?page_size=100')); Promise.all(requests).then((results) => { setProducts(results[0] as Paginated); setCustomers(results[1] as Paginated); setSuppliers(results[2] as Paginated); if (loadSites) setSites(results[3] as Paginated); }).catch((error) => notifications.show({ title: 'Unable to load form options', message: error instanceof Error ? error.message : 'Request failed.', color: 'red' })); }, [loadSites]);
  return { productOptions: products.results.map((row) => ({ value: String(row.id), label: `${row.name || row.id} · stock ${row.stock_quantity ?? '—'}` })), customerOptions: customers.results.map((row) => ({ value: String(row.id), label: `${row.name || row.id}${row.phone ? ` · ${row.phone}` : ''}` })), supplierOptions: suppliers.results.map((row) => ({ value: String(row.id), label: `${row.name || row.id}${row.phone ? ` · ${row.phone}` : ''}` })), siteOptions: sites.results.filter((row) => row.is_active !== false).map((row) => ({ value: String(row.id), label: `${row.name || row.id}${row.code ? ` · ${row.code}` : ''}${row.site_type ? ` · ${String(row.site_type).replaceAll('_', ' ')}` : ''}` })) };
}
function WorkflowHeader({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle: string }) { return <div><Text size="sm" c="indigo.3" fw={800}>{eyebrow}</Text><Title order={1} mt={4}>{title}</Title><Text c="dimmed" mt={4}>{subtitle}</Text></div>; }

export function CreateInvoicePage({ user }: { user: UserProfile }) {
  const canChooseSite = user.role?.scope !== 'site'; const { productOptions, customerOptions, siteOptions } = useOptions(canChooseSite); const [customer, setCustomer] = useState(''); const [site, setSite] = useState(''); const [lines, setLines] = useState<Line[]>([{ product: '', quantity: 1 }]); const [loading, setLoading] = useState(false);
  function updateLine(index: number, patch: Partial<Line>) { setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, ...patch } : line)); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!customer || (canChooseSite && !site) || lines.some((line) => !line.product || Number(line.quantity) < 1)) return; setLoading(true); try { await api.invoices.create({ customer: Number(customer), ...(site ? { site: Number(site) } : {}), items: lines.map((line) => ({ product: Number(line.product), quantity: Number(line.quantity) })) }); notifications.show({ title: 'Invoice created', message: 'The invoice is ready for confirmation.', color: 'teal' }); setLines([{ product: '', quantity: 1 }]); } catch (error) { notifications.show({ title: 'Invoice failed', message: error instanceof Error ? error.message : 'Request failed.', color: 'red' }); } finally { setLoading(false); } }
  return <Stack gap="xl"><WorkflowHeader eyebrow="SALES" title="New invoice" subtitle={canChooseSite ? 'Create a draft for the selected branch or store.' : `Create a draft for ${user.employee?.site?.name || 'your store'}.`} /><Card className="glass" withBorder radius="lg" p="xl" maw={980}><form onSubmit={submit}><Stack><SimpleGrid cols={{ base: 1, sm: canChooseSite ? 2 : 1 }}><Select label="Customer" searchable data={customerOptions} value={customer} onChange={(value) => setCustomer(value || '')} required />{canChooseSite && <Select label="Branch / store" searchable data={siteOptions} value={site} onChange={(value) => setSite(value || '')} required />}</SimpleGrid><Divider my="sm" /><Text fw={800}>Items</Text>{lines.map((line, index) => <SimpleGrid key={index} cols={{ base: 1, sm: 3 }}><Select label={`Product ${index + 1}`} searchable data={productOptions} value={line.product} onChange={(value) => updateLine(index, { product: value || '' })} required /><NumberInput label="Quantity" min={1} value={line.quantity} onChange={(value) => updateLine(index, { quantity: value })} required /><Group align="flex-end"><Button type="button" variant="subtle" color="red" disabled={lines.length === 1} onClick={() => setLines((current) => current.filter((_, lineIndex) => lineIndex !== index))}>Remove</Button></Group></SimpleGrid>)}<Button type="button" variant="light" onClick={() => setLines((current) => [...current, { product: '', quantity: 1 }])}>Add item</Button><Button type="submit" loading={loading} variant="gradient" gradient={{ from: 'indigo', to: 'cyan', deg: 120 }}>Create draft invoice</Button></Stack></form></Card></Stack>;
}

export function CreatePurchasePage({ user }: { user: UserProfile }) {
  const canChooseSite = user.role?.scope !== 'site'; const { productOptions, supplierOptions, siteOptions } = useOptions(canChooseSite); const [supplier, setSupplier] = useState(''); const [site, setSite] = useState(''); const [reference, setReference] = useState(''); const [lines, setLines] = useState<Line[]>([{ product: '', quantity: 1, unit_purchase_price: '', batch_number: '', manufactured_date: '', expiry_date: '' }]); const [loading, setLoading] = useState(false);
  function updateLine(index: number, patch: Partial<Line>) { setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, ...patch } : line)); }
  async function submit(event: FormEvent) { event.preventDefault(); const invalid = lines.some((line) => !line.product || Number(line.quantity) < 1 || line.unit_purchase_price === '' || Number(line.unit_purchase_price) < 0 || (line.manufactured_date && line.expiry_date && line.expiry_date < line.manufactured_date)); if (!supplier || (canChooseSite && !site) || invalid) return; setLoading(true); try { await api.purchases.create({ supplier: Number(supplier), ...(site ? { site: Number(site) } : {}), reference, items: lines.map((line) => ({ product: Number(line.product), quantity: Number(line.quantity), unit_purchase_price: Number(line.unit_purchase_price), ...(line.batch_number?.trim() ? { batch_number: line.batch_number.trim() } : {}), ...(line.manufactured_date ? { manufactured_date: line.manufactured_date } : {}), ...(line.expiry_date ? { expiry_date: line.expiry_date } : {}) })) }); notifications.show({ title: 'Purchase created', message: 'The purchase is ready for confirmation.', color: 'teal' }); setReference(''); setLines([{ product: '', quantity: 1, unit_purchase_price: '', batch_number: '', manufactured_date: '', expiry_date: '' }]); } catch (error) { notifications.show({ title: 'Purchase failed', message: error instanceof Error ? error.message : 'Request failed.', color: 'red' }); } finally { setLoading(false); } }
  return <Stack gap="xl"><WorkflowHeader eyebrow="PURCHASING" title="New purchase" subtitle={canChooseSite ? 'Receive stock with optional lot and expiry traceability.' : `Create a purchase for ${user.employee?.site?.name || 'your store'}.`} /><Card className="glass" withBorder radius="lg" p="xl" maw={1160}><form onSubmit={submit}><Stack><SimpleGrid cols={{ base: 1, sm: canChooseSite ? 2 : 1 }}><Select label="Supplier" searchable data={supplierOptions} value={supplier} onChange={(value) => setSupplier(value || '')} required />{canChooseSite && <Select label="Branch / store" searchable data={siteOptions} value={site} onChange={(value) => setSite(value || '')} required />}</SimpleGrid><TextInput label="Reference" value={reference} onChange={(event) => setReference(event.currentTarget.value)} /><Divider my="sm" /><Group justify="space-between" align="center"><div><Text fw={800}>Received items</Text><Text size="xs" c="dimmed">Record the supplier lot and dates when available. Expired batches will not be selected for normal stock issuance.</Text></div></Group>{lines.map((line, index) => <Card key={index} withBorder radius="lg" p="md" bg="transparent"><Stack gap="md"><SimpleGrid cols={{ base: 1, sm: 3 }}><Select label={`Product ${index + 1}`} searchable data={productOptions} value={line.product} onChange={(value) => updateLine(index, { product: value || '' })} required /><NumberInput label="Quantity" min={1} value={line.quantity} onChange={(value) => updateLine(index, { quantity: value })} required /><NumberInput label="Unit purchase price" min={0} value={line.unit_purchase_price} onChange={(value) => updateLine(index, { unit_purchase_price: value })} required /></SimpleGrid><SimpleGrid cols={{ base: 1, sm: 3 }}><TextInput label="Batch / lot number" placeholder="e.g. LOT-2026-09-A" value={line.batch_number} onChange={(event) => updateLine(index, { batch_number: event.currentTarget.value })} /><TextInput label="Manufactured date" type="date" value={line.manufactured_date} onChange={(event) => updateLine(index, { manufactured_date: event.currentTarget.value })} /><TextInput label="Expiry date" type="date" value={line.expiry_date} min={line.manufactured_date || undefined} onChange={(event) => updateLine(index, { expiry_date: event.currentTarget.value })} /></SimpleGrid><Group justify="flex-end"><Button type="button" variant="subtle" color="red" disabled={lines.length === 1} onClick={() => setLines((current) => current.filter((_, lineIndex) => lineIndex !== index))}>Remove item</Button></Group></Stack></Card>)}<Group justify="space-between" wrap="wrap"><Button type="button" variant="light" onClick={() => setLines((current) => [...current, { product: '', quantity: 1, unit_purchase_price: '', batch_number: '', manufactured_date: '', expiry_date: '' }])}>Add item</Button><Button type="submit" loading={loading} variant="gradient" gradient={{ from: 'violet', to: 'indigo', deg: 120 }}>Create draft purchase</Button></Group></Stack></form></Card></Stack>;
}

export function CollectPaymentPage() { const { customerOptions } = useOptions(); const [customer, setCustomer] = useState(''); const [cash, setCash] = useState<number | string>(0); const [transfer, setTransfer] = useState<number | string>(0); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); if (!customer || Number(cash) + Number(transfer) <= 0) return; setLoading(true); try { await api.payments.collections({ customer: Number(customer), cash_amount: Number(cash), transfer_amount: Number(transfer) }); notifications.show({ title: 'Payment collected', message: 'The payment was allocated automatically.', color: 'teal' }); setCash(0); setTransfer(0); } catch (error) { notifications.show({ title: 'Collection failed', message: error instanceof Error ? error.message : 'Request failed.', color: 'red' }); } finally { setLoading(false); } } const total = useMemo(() => Number(cash || 0) + Number(transfer || 0), [cash, transfer]); return <Stack gap="xl"><WorkflowHeader eyebrow="PAYMENTS" title="Collect payment" subtitle="Collect cash or bank transfer against the customer's oldest open invoices." /><Card className="glass" withBorder radius="lg" p="xl" maw={760}><form onSubmit={submit}><Stack><Select label="Customer" searchable data={customerOptions} value={customer} onChange={(value) => setCustomer(value || '')} required /><SimpleGrid cols={{ base: 1, sm: 2 }}><NumberInput label="Cash" min={0} value={cash} onChange={setCash} /><NumberInput label="Bank / transfer" min={0} value={transfer} onChange={setTransfer} /></SimpleGrid><Text ta="right" size="xl" fw={900}>Total: {total.toFixed(2)}</Text><Button type="submit" loading={loading}>Collect payment</Button></Stack></form></Card></Stack>; }

export function SupplierPaymentPage() { const { supplierOptions } = useOptions(); const [supplier, setSupplier] = useState(''); const [cash, setCash] = useState<number | string>(0); const [transfer, setTransfer] = useState<number | string>(0); const [reference, setReference] = useState(''); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); if (!supplier || Number(cash) + Number(transfer) <= 0) return; setLoading(true); try { await api.purchases.supplierPayment({ supplier: Number(supplier), cash_amount: Number(cash), transfer_amount: Number(transfer), reference }); notifications.show({ title: 'Supplier paid', message: 'The payment was allocated against open purchases.', color: 'teal' }); setCash(0); setTransfer(0); setReference(''); } catch (error) { notifications.show({ title: 'Supplier payment failed', message: error instanceof Error ? error.message : 'Request failed.', color: 'red' }); } finally { setLoading(false); } } return <Stack gap="xl"><WorkflowHeader eyebrow="PAYMENTS" title="Pay supplier" subtitle="Settle supplier payables using cash or bank transfer." /><Card className="glass" withBorder radius="lg" p="xl" maw={760}><form onSubmit={submit}><Stack><Select label="Supplier" searchable data={supplierOptions} value={supplier} onChange={(value) => setSupplier(value || '')} required /><SimpleGrid cols={{ base: 1, sm: 2 }}><NumberInput label="Cash" min={0} value={cash} onChange={setCash} /><NumberInput label="Bank / transfer" min={0} value={transfer} onChange={setTransfer} /></SimpleGrid><TextInput label="Reference" value={reference} onChange={(event) => setReference(event.currentTarget.value)} /><Button type="submit" loading={loading}>Pay supplier</Button></Stack></form></Card></Stack>; }
