# Generated by Django 6.0.8 on 2026-09-10 02:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(db_index=True, default='General', max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'name'),
                'indexes': [models.Index(fields=['name'], name='products_product_name_idx'), models.Index(fields=['category', 'name'], name='products_product_cat_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purchase_price__gte', Decimal('0'))), name='product_purchase_price_non_negative'), models.CheckConstraint(condition=models.Q(('selling_price__gte', Decimal('0'))), name='product_selling_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='CartonPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('units_per_carton', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('carton_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carton_pricings', to='products.product')),
            ],
            options={
                'verbose_name': 'Carton pricing',
                'verbose_name_plural': 'Carton pricings',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('carton_price__gte', Decimal('0'))), name='cartonpricing_carton_price_non_negative'), models.UniqueConstraint(fields=('product', 'name'), name='cartonpricing_unique_product_name')],
            },
        ),
    ]
